spring.cloud.gateway.server.webmvc.routes[0].id=USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/user/**
spring.cloud.gateway.server.webmvc.routes[1].id=PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/product/**
spring.cloud.gateway.server.webmvc.routes[2].id=STOCK-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://STOCK-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/stock/**
spring.cloud.gateway.server.webmvc.routes[3].id=ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/order/**
spring.cloud.gateway.server.webmvc.routes[4].id=PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/payment/**
app.jwt.secret=${JWT_SECRET:ZWNvbW1lcmNlLXNhZ2EtanNvbi13ZWItdG9rZW4tc2VjcmV0LWtleS1mb3ItYm9vdGNhbXAtcHJvamVjdC0xMjM0NTY=}
app.jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}
